[package]
name = "automation"
version = "0.1.0"
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"
readme = "README.md"
publish = false

[lib]
crate-type = ["cdylib"]
