[tasks.dev]
dependencies = ["format", "format-toml", "clippy", "build"]

[tasks.ci]
dependencies = [
  "print-env-flow",
  "check-format",
  "check-toml",
  "clippy",
  "build",
]

[tasks.check-toml]
condition = { env_set = ["CARGO_MAKE_FORMAT_TOML_FILES"] }
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = [
  "--help",
] }
command = "taplo"
args = ["format", "${CARGO_MAKE_FORMAT_TOML_FILES}", "--check"]

[tasks.clippy]
env = { CARGO_MAKE_CLIPPY_ARGS = "-- -D warnings" }

[tasks.build-external]
dependencies = ["build-release"]
command = "cp"
args = ["./target/release/libautomaton.so", "./puredata/automaton.pd_linux"]

[tasks.run]
dependencies = ["build-external"]
command = "pd"
args = ["puredata/main.pd"]
